CREATE TABLE IF NOT EXISTS postCategory(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  post_id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);